#!/bin/bash



echo 'running plan command...'

TODAY_DATE=$(date +"/%Y/%m/%d")
TODAY_YEAR=$(date +"/%Y")
PLANNER_DIR="$HOME/dotfiles/plan"
HIGHLIGHTS_DIR="$PLANNER_DIR/highlights"
NOTES_DIR="$PLANNER_DIR/notes"
TODO_DIR="$PLANNER_DIR/todo"
GOALS_DIR="$PLANNER_DIR/goals"
TODAYS_TODO_FILE="$TODO_DIR$TODAY_DATE.md"
TODAYS_HIGHLIGHTS_FILE="$HIGHLIGHTS_DIR$TODAY_YEAR.md"
TODAYS_NOTES_FILE="$NOTES_DIR$TODAY_DATE.md"
TODAYS_GOALS_FILE="$GOALS_DIR$TODAY_YEAR.md"


handle_missing_todo(){
    last_entry=$(find "$TODO_DIR" -type f -name "*.md" | sort | tail -n 1)
    echo "last planner entry: $last_entry"
    grep -v -E  "^-\s*\[[Xx]\]" "$last_entry" > "$TODAYS_TODO_FILE" 
}

case "$1" in 
    "todo")
        case "$2" in
            "")
            #TODO: right now it does a vim, make the default a cat, but make a flag for a vim
            if [[ -f "$TODAYS_TODO_FILE" ]]; then
                echo "file exists, open file"
                vim "$TODAYS_TODO_FILE"
            else
                echo "today's file doesn't exist, make new one"
                handle_missing_todo
            fi 
            ;;
            # TODO: add flags for different todo granularities, like a for all, d for directory
            "mark"|"m"|"-m"|"--mark")
                case "$3" in
                    "")
                        #TODO: enter mark mode
                        echo 'entering todo completion marker mode'
                        ;;
                    *)
                        if [[ "$3" =~ ^[0-9]+$ ]]; then
                            # TODO: check if the todo item exists, make todo items getter 
                            # if it does then remove and exit, if it doesn't then reply 
                            echo 'entered specific marker mode'
                        else
                            echo "unknown command: $3"
                        fi
                        ;;
                esac
                ;;
            "new"|"n"|"-n"|"--new")
                case "$3" in 
                    "today"|"t"|"-t"|"--t"|"--today") 
                        # TODO: insert next text in today's todo
                        echo "let's insert $4"
                        ;; 
                    "project"|"p"|"-p"|"--p"|"--project")
                        # TODO: insert next text in projects todo
                        ;;
                    "quick"|"q"|"-q"|"--q"|"--quick")
                        # TODO; same
                        ;;
                    "future"|"f"|"-f"|"--f"|"--future")
                        # TODO: same
                        ;;
                    *)
                        # TODO: insert into misc, but make sure it stops random commands
                        ;;
                esac
            ;;
        esac
    ;;
    "goals")
        if [[ -z $2 ]]; then 
            cat "$TODAYS_GOALS_FILE"
        else
            vim "$TODAYS_GOALS_FILE"
        fi
    ;;
    "highlights")
        echo "[$(date +"%Y-%m-%d")] $2" >> $TODAYS_HIGHLIGHTS_FILE
    ;;
    "notes")
        # No second argument? Default behavior
        if [[ -z "$2" ]]; then
            cat "$TODAYS_NOTES_FILE"
        elif [[ "$2" == "-v" ]]; then 
                vim "$TODAYS_NOTES_FILE"
        else
            # Append timestamped note
            note_text="${@:2}"  # everything after 'notes'
            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
            echo "[$timestamp] $note_text" >> "$TODAYS_NOTES_FILE"
        fi
    ;;

    "help"|"--help"|"")
        echo "  todo        Show today's todos"
        ;;
    *)
        echo "Unknown command: $1"
        echo "What are you trying to do :/"
        ;;
esac
